### ISSUE TITLE
untimeError: Function _RasterizeGaussiansBackward returned an invalid gradient at index 4 - got [130849, 1] but expected shape compatible with [130849, 2]

### ISSUE THREAD

**Issue by gwen233666** [lihaolin88/3D-Half-Gaussian-Splatting#1]
Hello, thank you for your excellent work, but I have encountered the problem as shown in the picture when replicating the code, I hope you can give me some advice, thank you!
![问题截图1](https://github.com/lihaolin88/3D-Half-Gaussian-Splatting/assets/130142345/0aac8968-8a46-4829-b49f-ad8f430068ce)

**Comment by lihaolin88** [comment]
Thank you for your interest in our work! Based on the error message, it appears that during the backward pass, the second dimension of the gradient is 1 instead of 2. This suggests that the rasterizer might be returning a parameter with the wrong shape.
Could you confirm if you ran the command "pip install ./submodules/diff-gaussian-rasterization" in the half Gaussian folder before executing the code? I suspect the environment might be using the Gaussian splatting rasterizer instead of our half Gaussian rasterizer.

**Comment by gwen233666** [comment]
Ok, thank you so much. In fact, the initial problem is as shown in the following figure. I have pip installed half Gaussian rasterizer again, but I don't know what the problem is.
![问题截图2](https://github.com/lihaolin88/3D-Half-Gaussian-Splatting/assets/130142345/4e44ea65-3062-40eb-8867-7aaab350045c)

**Comment by lihaolin88** [comment]
It appears that there might be an issue with the rasterizer installation. The error message indicates that the rasterizer may not be installed correctly. Could you please provide the installation details or screen shot when you installed the rasterizer?
I suspect that the system may have avoided installing the new rasterizer because it already has an existing rasterizer with the same name for Gaussian splatting. Can you also tell me if you installed the rasterizer for gaussian splatting before?

**Comment by gwen233666** [comment]
![问题截图3](https://github.com/lihaolin88/3D-Half-Gaussian-Splatting/assets/130142345/04801c10-091d-4c50-8c20-959ca5cd1bd8)
Okey, no problem, this is a screenshot of my installation at the time, but I did install the raster for gaussian splatting before~

**Comment by lihaolin88** [comment]
It seems you have created a virtual environment specifically for Half Gaussian, which is great. The rasterizer should be installed correctly in this environment.
Can you tell me if the rasterizer for Gaussian splatting is also installed in this virtual environment? If it is, I recommend creating a new virtual environment dedicated solely to Half Gaussian because two rasterizers may conflict. if no, can you show me a screenshot for function "rasterize_gaussians" in "./submodules/diff-gaussian-rasterization/diff_gaussian_rasterization/__init__.py" from your side

**Comment by gwen233666** [comment]
Thank you for your help! You are right, I copied the gaussian_splatting virtual environment directly with conda, it seems that there is a conflict between the two rasterizer installation, I configured the new virtual environment from scratch, he successfully trained, lucky as me

**Comment by lihaolin88** [comment]
Great! I am glad to hear that you have resolved the issue and hope that the half-Gaussian approach was helpful to you. I will proceed to close this issue now.
